---
title: "Resources"
---

I contributed to put together a way [more comprehensive list of resources](https://econthaki.github.io/recursos/2021/01/05/recursos.html) useful for Econ students in [EconThaki's website](https://econthaki.github.io/recursos/2021/01/05/recursos.html).

In this page, I will keep a list of some open resources for students available in the web related to topics I'm interested in. I'm including it in this section to have an easier access to them and to allow other people to know about them. 

Despite I am a strong supporter of MOOCs in platforms like [edX](https://www.edx.org/) and [Coursera](https://www.coursera.org/), I won't include their courses here because they are easier to find.

* Development Economics
  + [VDEV/CEPR/BREAD Virtual Development Economics Seminars](https://cepr.org/vdev-cepr-bread-seminars). Their YouTube playlist with past seminars is [here](https://www.youtube.com/playlist?list=PLt9jC4Ylzr6BP65E_ocYZH5luX8zIYctA).
  + [BREAD-IGC Virtual PhD Course](https://www.theigc.org/event/bread-igc-virtual-phd-course-spring-2022/). This course with modules on Education; Credit, insurance, and risk; and Migration is to be conducted in the Spring 2022 term. Try to register! But if you can't, let's wait for them to upload the material.
* International and Regional Economics
  + [AEA's webcast on International Trade, by Dave Donaldson and Marc Melitz](https://www.aeaweb.org/conference/cont-ed/2019-webcasts)
  + [Arnaud Costinot and Dave Donaldson’s PhD class materials](https://dave-donaldson.com/teaching/)
  + [Spatial Economics, by Stephen Redding](http://www.princeton.edu/~reddings/spatialeconomics.htm)
  + [Material for Trade PhD Students, by Stephen Redding](http://www.princeton.edu/~reddings/TradePhd.htm)
  + [Trade Diversion](https://tradediversion.net/) Commentary on development, globalization, and trade by Jonathan Dingel.
* Macroeconomics
  + [AEA's webcast on Inequality and Innovation, by Ufuk Akcigit and Stefanie Stantcheva](https://www.aeaweb.org/conference/cont-ed/2019-webcasts)
  + [Ben Moll's courses and lectures in distributional macroeconomics](https://benjaminmoll.com/lectures/)
  + [Lecture Videos, Code & Data from the Stanford Big-Data Initiative in International Macro-Finance](https://www.gsb.stanford.edu/faculty-research/faculty/conferences/big-data-initiative-international-macro-finance/videos-codes?undefined)
  + [STEG Virtual Course on Key Concepts in Macro Development](https://www.youtube.com/playlist?list=PLt9jC4Ylzr6BuFVwZNW0hCJureBVMBJ-Z)
* Coding Tools for Economics and Statistics
  + [Quant Econ](https://quantecon.org/): Open code resources for economic modelling and data science using Python and Julia.
  + [Julia Academy](https://juliaacademy.com/)
  + [Data Visualization in R, by Andrew Heiss](https://datavizm20.classes.andrewheiss.com/schedule/) 
  + [Tutorial Stata to Python from Daniel Sullivan](http://www.danielmsullivan.com/pages/tutorial_stata_to_python.html)

